version: '3.0'
services:
  morqa:
    image: mysteriumnetwork/quality-oracle:latest
    command: >
      --bind-addr=:8085
      --prometheus=http://prometheus:9090
      --metrics-addr=:8080
    depends_on:
      - prometheus
    expose:
      - 8085
      - 8080

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./e2e/prometheus:/prometheus
    command:
      - '--config.file=/prometheus/config.yml'
      - '--storage.tsdb.path=data/'
    expose:
      - 9090

  ipify:
    image: owlab/ipify
    expose:
      - 3000

  broker:
    image: nats:1.0.4
    expose:
      - 4222
      - 8222

  db:
    image: percona:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  mysterium-api:
    image: mysteriumnetwork/mysterium-api:latest
    expose:
      - 8001
    environment:
      APP_PORT: 8001
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "ws://ganache:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
      DISCOVERY_VERIFY_IDENTITY: "false"
    depends_on:
      - db
      - ganache

  #private blockchain
  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    expose:
      - 8545
    command: >
      --mnemonic "amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger"

  trust:
    image: mysteriumnetwork/trust-oracle:latest
    command: >
      -swaggerHost=trust
      -trustedIDs=0xc4cb9a91b8498776f6f8a0d5a2a23beec9b3cef3

  transactor:
    image: mysteriumnetwork/transactor:0.4.4
    environment:
      PORT: 8888
    expose:
      - 8888
    depends_on:
      - ganache
      - mongodb
      - redis
    command: >
      -settlemntFee 1000
      -topUpAmount 7000000000000000000
      -stakeAmount 62000000000000000000
      -stakeDecreaseFee 1
      -mystSCAddress 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint ws://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -ourIdentity 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -balanceCheckInterval 1s
      -MongoUser transactor
      -MongoPass transactor
      -MongoHost mongodb:27017
      -MongoReplSet ""
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore

  redis:
    image: bitnami/redis:5.0.8
    container_name: 'hermes_redis'
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  hermes:
    image: mysteriumnetwork/hermes:v3-dev
    environment:
      PORT: 8889
    expose:
      - 8889
    depends_on:
      - ganache
      - redis
      - mongodb
    command: >
      -identityPassphrase ""
      -myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint ws://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -operator 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -keystoreDir /keystore
      -hermesAddress 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -bcDataRefreshInterval 1ns
      -MongoUser hermes
      -MongoPass hermes
      -MongoHost "mongodb:27017"
      -MongoDatabase hermes
      -MongoReplSet ""
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore

  hermes2:
    image: mysteriumnetwork/hermes:v3-dev
    environment:
      PORT: 8889
    expose:
      - 8889
    depends_on:
      - ganache
      - redis
      - mongodb
    command: >
      -identityPassphrase ""
      -myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint ws://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -operator 0x761f2bb3e7ad6385a4c7833c5a26a8ddfdabf9f3
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -keystoreDir /keystore
      -hermesAddress 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -bcDataRefreshInterval 1ns
      -MongoUser hermes2
      -MongoPass hermes2
      -MongoHost "mongodb:27017"
      -MongoDatabase hermes2
      -MongoReplSet ""
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore

  mongodb:
    image: 'mongo:4.2.3'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=hermes
      - MONGO_NON_ROOT_USERNAME=hermes
      - MONGO_NON_ROOT_PASSWORD=hermes
    expose:
      - 27017
      - 27018
      - 27019
    volumes:
      - ./e2e/mongo-init.e2e.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  myst-provider:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - hermes2
      - morqa
      - trust
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 1194
      - 4050
    volumes:
      - ./e2e/myst-provider/keystore:/var/lib/mysterium-node/betanet/keystore
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-land
      --firewall.protected.networks=""
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --hermes.hermes-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --transactor.address=http://transactor:8888/api/v1
      --keystore.lightweight
      --log-level=debug
      --quality.address=http://morqa:8085/api/v1
      --payments.provider.invoice-frequency=1s
      --access-policy.address=http://trust:8080/api/v1/access-policies/
      --access-policy.fetch=1s
      service
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000
      openvpn,noop,wireguard

  myst-consumer-noop:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    volumes:
      - ./e2e/myst-consumer/keystore:/var/lib/mysterium-node/betanet/keystore
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - myst-provider
      - morqa
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --hermes.hermes-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --transactor.address=http://transactor:8888/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v1
      daemon

  myst-consumer-hermes2:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes2
      - myst-provider
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --hermes.hermes-id=0x55fB2d361DE2aED0AbeaBfD77cA7DC8516225771
      --transactor.address=http://transactor:8888/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v1
      daemon

  myst-consumer-openvpn:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - myst-provider
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --hermes.hermes-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --transactor.address=http://transactor:8888/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v1
      daemon

  myst-consumer-wireguard:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - myst-provider
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --hermes.hermes-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --transactor.address=http://transactor:8888/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://mysterium-api:8001/v1
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v1
      daemon

  #go runner to run go programs inside localnet (usefull for contract deployment or e2e test running)
  go-runner:
    build:
      context: .
      dockerfile: ./e2e/gorunner/Dockerfile.precompiled
    cap_add:
      - NET_ADMIN
    volumes:
      - ./e2e/blockchain/keystore:/node/keystore
    working_dir: /node
